#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

TEST_DESCRIPTION = "Python script as a test, hello world example"

if 1+1 == 2:
    sys.exit(0)
else:
    sys.exit(1)


# vim: ft=python
